# Generated by Django 2.2 on 2019-04-07 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('_answers', models.CharField(max_length=200)),
                ('_choices', models.CharField(max_length=200)),
                ('isMultipleChoice', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preface', models.TextField(max_length=500)),
                ('_graph', models.TextField(max_length=1000)),
                ('sourceNode', models.IntegerField()),
                ('questions', models.ManyToManyField(to='Viz.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_attempted_answers', models.CharField(db_column='attempted_answers', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viz.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_answers', models.CharField(max_length=20)),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(verbose_name=models.DateTimeField(auto_now_add=True))),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viz.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
