# Generated by Django 2.2 on 2019-04-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscores',
            name='attempted_answers',
        ),
        migrations.AddField(
            model_name='quizscores',
            name='attempted_answers',
            field=models.ManyToManyField(to='Viz.AttemptedQuestion'),
        ),
    ]
