# Generated by Django 2.2 on 2019-04-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Viz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
